theme: jekyll-theme-minimal
# Site settings
title: My Blog
SEOTitle: 我的博客 | My Blog
header-img: img/post-bg-desk.jpg
email: 暂无
description: "写一句你想写的话"
keyword: "我的博客"
url: "http://name.github.io"          # name改成你的ID
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/name/name.github.io.git" # 用你的ID替换name

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "苟利国家生死以，岂因祸福避趋之~"
sidebar-avatar: /img/avatar_binggan.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`

  # SNS settings
RSS: false
# weibo_username: 暂无
zhihu_username:     暂无
github_username:    暂无
facebook_username:  暂无
jianshu_username:   暂无
  #twitter_username: 暂无